# Generated by Django 4.2.6 on 2023-12-23 10:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Points",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Point", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Main_Title", models.CharField(max_length=200)),
                ("Sub_Title", models.CharField(max_length=200)),
                ("Category", models.CharField(max_length=100)),
                ("Heading", models.CharField(max_length=100)),
                ("Paragraph1", models.TextField()),
                ("img", models.ImageField(default=True, upload_to="images/")),
                (
                    "point",
                    models.ManyToManyField(related_name="blogs", to="Blog_app.points"),
                ),
            ],
        ),
    ]
