# Generated by Django 4.2.6 on 2023-12-24 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Blog_app", "0002_alter_points_point"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="Paragraph2",
            field=models.TextField(default=True),
        ),
        migrations.RemoveField(
            model_name="blog",
            name="point",
        ),
        migrations.AddField(
            model_name="blog",
            name="point",
            field=models.ForeignKey(
                default=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blogs",
                to="Blog_app.points",
            ),
        ),
    ]
