# Generated by Django 4.2.6 on 2023-12-24 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Blog_app", "0004_remove_blog_point_remove_points_point_points_point"),
    ]

    operations = [
        migrations.AlterField(
            model_name="points",
            name="point",
            field=models.ForeignKey(
                default=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="points",
                to="Blog_app.blog",
            ),
        ),
    ]
