# Generated by Django 4.2.6 on 2023-12-24 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Blog_app", "0005_alter_points_point"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="points",
            field=models.ForeignKey(
                default=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="points",
                to="Blog_app.points",
            ),
        ),
        migrations.AlterField(
            model_name="points",
            name="point",
            field=models.CharField(max_length=500),
        ),
    ]
