# Generated by Django 4.2.6 on 2023-12-24 08:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Blog_app", "0007_alter_blog_points"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="points",
        ),
        migrations.AddField(
            model_name="blog",
            name="points",
            field=models.ManyToManyField(to="Blog_app.points"),
        ),
    ]
