# Generated by Django 4.2.6 on 2023-12-24 08:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Blog_app", "0008_remove_blog_points_blog_points"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="Paragraph2",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="blog",
            name="img",
            field=models.ImageField(upload_to="images/"),
        ),
    ]
