# Generated by Django 4.2.6 on 2023-12-24 08:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Blog_app", "0009_alter_blog_paragraph2_alter_blog_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="img",
            field=models.FileField(upload_to="images/"),
        ),
    ]
