# Generated by Django 4.2.6 on 2023-12-27 17:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Blog_app", "0013_blog_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="Highlight",
            field=models.CharField(default="Text", max_length=200),
        ),
    ]
