# Generated by Django 4.2.6 on 2023-12-28 07:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Blog_app", "0016_alter_blog_paragraph1_alter_blog_paragraph2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="Paragraph1",
            field=models.TextField(max_length=10),
        ),
    ]
