# Generated by Django 4.2.6 on 2023-12-28 09:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Blog_app", "0019_alter_blog_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 12, 28, 14, 44, 19, 642978)
            ),
        ),
    ]
