# Generated by Django 4.2.6 on 2023-12-28 09:24

import Blog_app.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Blog_app", "0020_blog_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 12, 28, 14, 54, 55, 282949)
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="img",
            field=models.ImageField(
                default="images",
                upload_to="images/",
                validators=[Blog_app.models.validate_image_size],
            ),
        ),
    ]
