# Generated by Django 4.2.6 on 2023-12-28 09:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Blog_app", "0021_alter_blog_created_at_alter_blog_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 12, 28, 15, 24, 43, 862653)
            ),
        ),
        migrations.AlterField(
            model_name="points",
            name="point",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
