# Generated by Django 4.2.6 on 2023-12-29 10:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Blog_app", "0022_alter_blog_created_at_alter_points_point"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="Highlight",
            field=models.CharField(default="Text", max_length=1000),
        ),
        migrations.AlterField(
            model_name="blog",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 12, 29, 16, 21, 47, 338762)
            ),
        ),
    ]
