# Generated by Django 4.2.6 on 2023-12-30 09:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Blog_app", "0023_alter_blog_highlight_alter_blog_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="name", max_length=100)),
                ("email", models.EmailField(default="email", max_length=100)),
                ("comment", models.TextField(default="comment")),
            ],
        ),
        migrations.AlterField(
            model_name="blog",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 12, 30, 15, 7, 38, 234960)
            ),
        ),
        migrations.AddField(
            model_name="blog",
            name="comments",
            field=models.ManyToManyField(
                blank=True, default="comment", to="Blog_app.comments"
            ),
        ),
    ]
