# Generated by Django 4.2.6 on 2023-12-30 09:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Blog_app", "0024_comments_alter_blog_created_at_blog_comments"),
    ]

    operations = [
        migrations.CreateModel(
            name="contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("company", models.CharField(blank=True, max_length=100)),
                ("phone", models.CharField(blank=True, max_length=10)),
                (
                    "email",
                    models.EmailField(blank=True, default="email", max_length=100),
                ),
                ("interested", models.CharField(blank=True, max_length=500)),
                ("message", models.TextField(default="comment")),
            ],
        ),
        migrations.AlterField(
            model_name="blog",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 12, 30, 15, 26, 48, 525938)
            ),
        ),
    ]
