# Generated by Django 4.2.6 on 2024-01-01 10:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Blog_app", "0025_contact_alter_blog_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 1, 15, 59, 16, 286387)
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="company",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.EmailField(default="email", max_length=100),
        ),
        migrations.AlterField(
            model_name="contact",
            name="first_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="contact",
            name="interested",
            field=models.CharField(
                choices=[
                    ("RM", "MaleRisk Management"),
                    ("TC", "Traditional Counsuling"),
                    ("PM", "Portfilio Management"),
                    ("AA", "Aset Allocation"),
                ],
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="message",
            field=models.TextField(blank=True, default="comment"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="phone",
            field=models.CharField(max_length=10),
        ),
    ]
