# Generated by Django 4.2.6 on 2024-01-01 10:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Blog_app", "0026_alter_blog_created_at_alter_contact_company_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Apointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100)),
                ("phone", models.CharField(blank=True, max_length=10)),
                (
                    "email",
                    models.EmailField(blank=True, default="email", max_length=100),
                ),
                (
                    "subjects",
                    models.CharField(
                        choices=[
                            ("RM", "MaleRisk Management"),
                            ("TC", "Traditional Counsuling"),
                            ("PM", "Portfilio Management"),
                            ("AA", "Aset Allocation"),
                        ],
                        max_length=500,
                    ),
                ),
                ("message", models.TextField(default="comment")),
            ],
        ),
        migrations.AlterField(
            model_name="blog",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 1, 16, 2, 51, 177363)
            ),
        ),
    ]
