# Generated by Django 5.0.1 on 2024-01-03 05:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Blog_app", "0027_apointment_alter_blog_created_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blog",
            old_name="Heading",
            new_name="Points_Heading",
        ),
        migrations.AlterField(
            model_name="blog",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 3, 11, 14, 3, 835487)
            ),
        ),
    ]
