# Generated by Django 5.0.1 on 2024-01-03 05:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Blog_app", "0028_rename_heading_blog_points_heading_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 3, 11, 15, 8, 268154)
            ),
        ),
    ]
